title: Otvoreni Dani Nauke 2019 
subtitle: Primjeri ucenja reprezentacija
description: Demo naucenih reprezentacija i njihovih primjena
author: Sandra Mitrovic
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
