title: Otvoreni Dani Nauke 2019  
description: Primjeri ucenja reprezentacija   
subtitle: Demo naucenih reprezentacija i njihovih primjena
author: Sandra Mitrovic
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
